### ISSUE TITLE
No callbacks after switch off and on of a player at the event node

### ISSUE THREAD

**Issue by bwatconbee** [hklages/node-red-contrib-sonos-events#13]
Before I start with my problem, first of all my greatest respect for the work done on the whole nodes for nodered! But now my problem: I run nodered on a raspi, which runs permanently. Only my Sonos system, for example, is switched off overnight. If Nodered is started or deployed, the event node works fine! All subscribed events arrive in the Nodered system. However, if the Sonos Player is turned off and turned on again the next morning, the event node will no longer establish a new connection to the Sonos Player. Only switching off the raspi or manually restarting the nodered system will lead to a new connection. Is there a solution to this problem? My suggestion: Wouldn't it make sense to equip the event node with an input in order to then re-register the callbacks on the player if necessary, e.g. if a ping to the player is successful again? I would be very happy to receive an answer!

**Comment by hklages** [comment]
Hi.

It is exactly as you described it. If a SONOS speaker is disconnected from
power, the "subscription" gets lost and will never be restored. (That's why
SONOS speakers don't have an "off switch" :-)

At the moment I couldn't find any solution to the problem. I am in Colombia
right now and have no chance to try and test any work around. So it will
take some time, at least until mid-February.

Idea: NodeRED has the ability to “redeploy” a single node. Maybe we can use
this function.
An input node will probably not work because the deployment starts a server
that creates the subscription. I can't imagine doing this with an incoming
message.

kind regards, Henning

**Comment by hklages** [comment]
Any development of this package is stopped.
