### ISSUE TITLE
Sonos port is regularly no longer recognized and displayed as disconnected in „events“ node

### ISSUE THREAD

**Issue by Tonitom** [hklages/node-red-contrib-sonos-events#16]
### Description

Sonos Port is regularly no longer recognized and displayed as disconnected in „events“ node.
All other Player are fine. Restarting Flows solves the problem.

### What node/command (topic)/state (payload)

node: events
command:
state: disconnected, invalid player timeout

### In case of a bug: Are you able to reproduce the error

Happens randomly, no pattern seen

### Versions and Infrastructure

VM on Synology
node-red-contrib-sonos-events v 1.2.3
NodeRed 3.1.9

see: [https://flows.nodered.org/flow/a5c42641bf33dd0da9bfd4426a06950a]

**Comment by hklages** [comment]
Hi. "Randomly" is difficult to fix. I need more information. 
Please send a screen shot. On what events do you subscribe?

**Comment by Tonitom** [comment]
Hallo,
I hope my information helps. 
Even if the player is shown here as disconnected, it works in the Sonos app and with the “Universal Node”. 

1. the player is connected via Lan, could this be the cause? Maybe that it switches between Lan and Wlan? 
2. maybe I just need to find a way to restart the node after a timeout.

![image](https://github.com/hklages/node-red-contrib-sonos-events/assets/45144440/0f7d4f8f-c7e3-4977-ab6d-6cf3c4bfad26)
![image](https://github.com/hklages/node-red-contrib-sonos-events/assets/45144440/f3b7ccd9-354d-4218-9054-45cc5d194ca2)

Tonitom

**Comment by Tonitom** [comment]
Ok, probably that's the solution, I shouldn't go for the IP address, but the name. 

Thanks for finding it.

**Comment by hklages** [comment]
> I shouldn't go for the IP address, but the name.

If you provide a DNS name, the package just does a "dnsPromises.resolve4" to get the ip address from your DNS server. Finally in both cases the ip address is used. Anyway DNS is a good idea because it is better to remember and "static". 

The shown error message " .... error or timed out" should only appear a few seconds (exactly 4) after you did a deployment of that node. It should never happen that first  a "connected at 6329" shows up and after some hours the "... error or timed out" appears.  
**Can you verify that?** 

How many sonos-plus or sonos-events nodes do you have? I guess a lot.  
During deployment for every node there is a request being send to the SONOS player. If there are a lot of requests the SONOS player is not able to handle them and that causes the "... error or timed out" message on some nodes. 
For universal/mysonos nodes you can **tic the "Do NOT check the availability of Sonos-Player."** That will reduce the traffic and hopefully your SONOS player is able to handle all request. 
If even that does not solve the problem we can try to increase the time out time from currently 4 seconds.

**Comment by Tonitom** [comment]
After the deployment, all players are reachable and show "connected at 6329". The player is in a group with an old Play:1, and the Play:1 regularly executes the "joiner.play.notification", which might have disrupted the network. Now, while summarizing, I also remembered that my Pioneer AVR with "Works with Sonos" sometimes loses connection to the Sonos Port and fails to switch inputs.

I have about 30 universal nodes und 7 Events nodes

I've now assigned the player names in my Fritz!Box interface. Unfortunately, I couldn't find a way to directly change the device names.
I'm confident that the name resolution will fix the issue. If everything works as expected, I'll provide a short update in a few days. Otherwise, I'll reach out for support sooner.

Thanks
Tonitom

**Comment by Tonitom** [comment]
Something strange, 2-3 days ago I copied the node into another flow, in one flow it's still active, in the other it's disconnected. I'll start activating the "Do NOT check the availability of Sonos-Player".

![image](https://github.com/hklages/node-red-contrib-sonos-events/assets/45144440/ebb324b5-cc92-4cff-9dc6-9a435330306d)

**Comment by hklages** [comment]
For testing, I suggest that you use the deploy button always  with  "full".
Then you can better see what nodes throw an error.

**Comment by Tonitom** [comment]
Ok, I will test.

And is there a replacement for AVTransport content - msg.payload.enqueuedTitle? (Playlist name)

**Comment by hklages** [comment]
> And is there a replacement for AVTransport content - msg.payload.enqueuedTitle? (Playlist name)

What do you mean? I dont understand that. What do you want tondo?

**Comment by Tonitom** [comment]
The Events node for "AVTransport content: track, album..." used to include "enqueuedTitle" in its payload, representing the Sonos playlist. Unfortunately, the enqueuedTitle is now missing from the payload.

My use case
When using the Universal node to start a playlist from my Sonos favorites, I receive the current track via the Event node, and previously, I also got the name of the playlist. Previously, I could restart the playlist and continue from the last played track. However, for some time now, the name of the playlist is no longer being retrieved.

From my old test system with "sonos-events" version 1.2.1
![image](https://github.com/hklages/node-red-contrib-sonos-events/assets/45144440/46533c36-92d1-4539-b94f-f86336cecff6)

**Comment by hklages** [comment]
.... I am abroad without laptop. I'm going to check it on Friday.
What kind of playlists? music library, you tube, SONOS playlists?

**Comment by Tonitom** [comment]
I use Apple Music. Whether I'm playing self-made playlists in Apple Music or Apple stations, with version 1.2.1, it's correctly outputted in the payload.

**Comment by hklages** [comment]
I can reproduce the error and also that it works in 1.2.1. 
Have to report an error in ts-sonos.

**Comment by guenter-ms** [comment]
Hello,

I have exactly the same problem. I only have one Sonos event node. When "disconnected" is shown, only nodered redeployment will fix it to "connected" and the Sonos universal nodes will work again. Reading the posts before, I do not see the solution. I cannot reproduce but will get the error every 2 or 3 days. The player is reachable by Sonos app and permanently powered on an is on WLAN.

What can I do?





![Bildschirmfoto 2024-06-08 um 08 28 14](https://github.com/hklages/node-red-contrib-sonos-events/assets/6253315/f8b7b284-40a1-4d42-ad95-d2c11733b2f8)


![Bildschirmfoto 2024-06-08 um 08 30 19](https://github.com/hklages/node-red-contrib-sonos-events/assets/6253315/481c23be-fa83-4028-991d-33e69b0e03c4)


![Bildschirmfoto 2024-06-08 um 08 35 54](https://github.com/hklages/node-red-contrib-sonos-events/assets/6253315/a118930c-8858-408d-a03a-d467731da82f)

**Comment by hklages** [comment]
Hi @guenter-ms 
The error message only shows up during the deployment of that node - most likely because the network is overloaded / to many nodes send requests to a SONOS player. So any time you deploy the node please check it.   

Usually it helps if you tic the "Do NOT check the availability of Sonos-Player." in many or all of your sonos-plus nodes. That reduced the load at the SONOS player and when you deploy the sonos-event node there is bandwidth to fullfill the request. 

Is that understandable? Does it solve the issue?

**Comment by guenter-ms** [comment]
Thats OK. Thank you

**Comment by hklages** [comment]
@Tonitom : I rolled back to ts-sonos 2.5 - that was the base for 1.2.1. 

Hope all works now.
